# Generated by Django 4.2.16 on 2026-09-30 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditreview",
            name="biz_id",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="creditreview",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="credit_score",
            field=models.IntegerField(
                default=600,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreview",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="credit_review_score_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreview",
            constraint=models.CheckConstraint(
                check=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="credit_review_users_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="pilotprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("years_exp__gte", 0)),
                name="pilot_years_exp_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="pilotprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="pilot_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pilotprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lng__isnull", True),
                    models.Q(("lng__gte", -180), ("lng__lte", 180)),
                    _connector="OR",
                ),
                name="pilot_lng_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreview",
            constraint=models.CheckConstraint(
                check=models.Q(("biz_id__gt", 0)),
                name="credit_review_biz_id_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.CheckConstraint(
                check=models.Q(("credit_score__gte", 300), ("credit_score__lte", 1000)),
                name="user_credit_score_300_1000",
            ),
        ),
    ]
