# Generated by Django 4.2.16 on 2026-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_review_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseprofile",
            name="business_license_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="legal_id_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="legal_representative",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="review_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "待完善"),
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已驳回"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enterpriseprofile",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="authorized_work_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="dispatch_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
