# Generated by Django 4.2.16 on 2026-09-30 05:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_workorder_enterprise_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("100.00")),
                    django.core.validators.MaxValueValidator(Decimal("9999999999.99")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="ordermatchlog",
            constraint=models.UniqueConstraint(
                fields=("order", "pilot"), name="unique_order_pilot_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordermatchlog",
            constraint=models.CheckConstraint(
                check=models.Q(("distance_km__gte", 0)),
                name="match_distance_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordermatchlog",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="match_score_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pilot_income__gte", 0),
                    ("platform_fee__gte", 0),
                    ("total_amount__gte", 0),
                ),
                name="settlement_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(("budget__gte", Decimal("100.00"))),
                name="work_order_budget_min_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(("match_radius_km__gt", 0)),
                name="work_order_match_radius_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("platform_fee_rate__gte", 0), ("platform_fee_rate__lte", 1)
                ),
                name="work_order_fee_rate_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("balance_amount__gte", 0),
                    ("cancellation_penalty__gte", 0),
                    ("deposit_amount__gte", 0),
                    ("escrow_amount__gte", 0),
                ),
                name="work_order_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lat__isnull", True),
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    _connector="OR",
                ),
                name="work_order_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lng__isnull", True),
                    models.Q(("lng__gte", -180), ("lng__lte", 180)),
                    _connector="OR",
                ),
                name="work_order_lng_range",
            ),
        ),
    ]
