# Generated by Django 4.2.16 on 2026-10-02 16:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_airspace_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="abnormal_evidence",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workorder",
            name="abnormal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workorder",
            name="acceptance_checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workorder",
            name="acceptance_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workorder",
            name="acceptance_result",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="workorder",
            name="review_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workorder",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="risk_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workorder",
            name="risk_level",
            field=models.CharField(blank=True, default="low", max_length=16),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="platform_fee_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.1000"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "待平台审核"),
                    ("pending", "待匹配"),
                    ("matched", "已推送"),
                    ("accepted", "已接单"),
                    ("declared", "已申报"),
                    ("arrived", "飞手已到达"),
                    ("working", "作业中"),
                    ("finished", "作业已完成"),
                    ("submitted", "待验收"),
                    ("reviewed", "管理员已审核"),
                    ("accepted_done", "已验收"),
                    ("settled", "已结算"),
                    ("rectifying", "整改中"),
                    ("disputed", "争议处理中"),
                    ("aborted", "异常中止"),
                    ("refunded", "已退款"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "account_hint",
                    models.CharField(blank=True, default="模拟账户", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已到账"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("title", models.CharField(max_length=128)),
                ("tax_no", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开票"),
                            ("issued", "已开票"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invoice_url", models.URLField(blank=True, default="")),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
