# Generated by Django 4.2.16 on 2026-09-30 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="salary_max",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(3000),
                    django.core.validators.MaxValueValidator(1000000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="salary_min",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(3000),
                    django.core.validators.MaxValueValidator(1000000),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="agencyfee",
            constraint=models.CheckConstraint(
                check=models.Q(("fee_rate__gte", 0), ("fee_rate__lte", 1)),
                name="agency_fee_rate_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="agencyfee",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)), name="agency_fee_amount_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.CheckConstraint(
                check=models.Q(("match_score__gte", 0), ("match_score__lte", 100)),
                name="job_match_score_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobpost",
            constraint=models.CheckConstraint(
                check=models.Q(("salary_min__gte", 3000), ("salary_min__lte", 1000000)),
                name="job_salary_min_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobpost",
            constraint=models.CheckConstraint(
                check=models.Q(("salary_max__gte", 3000), ("salary_max__lte", 1000000)),
                name="job_salary_max_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobpost",
            constraint=models.CheckConstraint(
                check=models.Q(("salary_max__gte", models.F("salary_min"))),
                name="job_salary_ordered",
            ),
        ),
    ]
