# Generated by Django 4.2.16 on 2026-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalorder",
            name="credit_score_snapshot",
            field=models.IntegerField(default=600),
        ),
        migrations.AddConstraint(
            model_name="dronedevice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("daily_price__gte", 0),
                    ("deposit__gte", 0),
                    ("depreciation__gte", 0),
                    ("monthly_price__gte", 0),
                ),
                name="device_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dronedevice",
            constraint=models.CheckConstraint(
                check=models.Q(("stock__gte", 0)), name="device_stock_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancerecord",
            constraint=models.CheckConstraint(
                check=models.Q(("cost__gte", 0)), name="maintenance_cost_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalorder",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="rental_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("damage_fee__gte", 0),
                    ("deposit_paid__gte", 0),
                    ("insurance_fee__gte", 0),
                    ("rent_amount__gte", 0),
                ),
                name="rental_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("credit_score_snapshot__gte", 300),
                    ("credit_score_snapshot__lte", 1000),
                ),
                name="rental_credit_score_300_1000",
            ),
        ),
    ]
